# Generated by Django 5.2.3 on 2025-06-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_subject_chapters_subject_code_subject_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
