# Generated by Django 5.2.3 on 2025-06-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_subject_description_alter_chapter_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
